version: "2.2"

services:
  app:
    container_name: "${SERVICE_NAME}"
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
    #environment:
    # - DB_HOST=mongodb
    # - DB_USER=$MONGODB_USER
    # - DB_PASSWORD=$MONGODB_PASSWORD
    # - DB_NAME=$MONGODB_DATABASE
    # - DB_PORT=$MONGODB_DOCKER_PORT
    stdin_open: true
    tty: true
    command: npm start
    depends_on:
      - mongodb
    restart: unless-stopped
    volumes:
      - ./app-data:/usr/src/app
    networks:
      - dl-net

  mongodb:
    image: mongo:latest
    env_file:
      - .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    ports:
      - $MONGODB_LOCAL_PORT:27017
    volumes:
      - ./mong-db-data:/data/db
    networks:
      - dl-net

# volumes:
#   app-data:
#   db:

networks:
  dl-net:
    driver: bridge
